/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System Memory calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdio.h>

/* Variables */
extern int errno;
//register char * stack_ptr asm("sp");

/* Functions */

/**
 _sbrk
 Increase program data space. Malloc and related functions depend on this
**/
#ifdef USE_STM32F769I_DISCO
caddr_t _sbrk(int incr)
{
	extern char __heap_start asm("__heap_start"); // Defined by the linker.
	extern char __heap_limit asm("__heap_limit"); // Defined by the linker.

	static char *heap_end;
    static char *heap_limit = &__heap_limit;

	char *prev_heap_end;

	if (heap_end == 0)
		heap_end = &__heap_start;

	prev_heap_end = heap_end;
	if (heap_end + incr > heap_limit)
	{
		errno = ENOMEM;
		return (caddr_t) -1;
	}

	heap_end += incr;

	return (caddr_t) prev_heap_end;
}
#endif
#ifdef USE_STM32746G_DISCOVERY
/* Author: Florian */

#define HEAP_SIZE		0x00700000 // 7 MB

/* heap */
__attribute__ ((section(".sdram")))
static char heap[HEAP_SIZE];

/* pointer to current position in heap */
static char* _cur_brk = heap;

caddr_t _sbrk_r (struct _reent* r, int incr)
{
	char* _old_brk = _cur_brk;

	if ((_cur_brk + incr) > (heap + HEAP_SIZE))
	{
		uint8_t i;

		char* msg = "HEAP FULL!\r\n";

		/*for (i = 0; i < strlen(msg); i++)
		{
			debug_chr (msg[i]);
		}*/

		errno = ENOMEM;
		return (void *)-1;
	}

	_cur_brk += incr;

	return (caddr_t)_old_brk;
}
#endif


